[package]
name = "loom"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.36"
crossbeam-channel = "0.5.15"
env_logger = "0.11.8"
libc = "0.2.172"
log = "0.4.27"
parking_lot = "0.12.3"
rustfft = "6.2.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
